name: 'Terraform Utils'
description: 'Terraform Utils'
runs:
  using: 'composite'
  steps:
    - name: Create Terraform Plugin Cache Dir
      run: mkdir --parents $TF_PLUGIN_CACHE_DIR
    - name: Cache Terraform plugins
      uses: actions/cache@v4
      with:
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
        key:  ${{ runner.os }}${{ runner.arch }}-terraform
        restore-keys: |
          ${{ runner.os }}${{ runner.arch }}-terraform
  # - task: DownloadSecureFile@1
  #   name: local_k8s_config
  #   inputs:
  #     secureFile: 'local_k8s_config'
  #     retryCount: '8'
  #   displayName: 'Download secure file - local_k8s_config'
  # - task: PowerShell@2
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       New-Item -ItemType Directory -Force -Path ~/.kube
  #       Move-Item -Path $(local_k8s_config.secureFilePath) -Destination ~/.kube/config -Force
  #       (Get-Content ~/.kube/config) -replace "127\.0\.0\.1", "172.18.224.242" | Set-Content ~/.kube/config
  #   displayName: 'Copy and configure Kubeconfig file'