name: Docker
on:
  workflow_dispatch:
jobs:
  docker:
    name: Docker
    runs-on: 'arc-desktop-s8glse7'
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'TEST'
        run: |
          pwd
          ls -larth
          docker --version
      # - name: 'Build'