name: 'Docker - Build And Push'
on:
  workflow_dispatch:
    inputs:
      docker_repository:
        description: 'Set the Docker Repository to use'
        type: choice
        required: true
        default: 'ghcr.io/create-the-roaring-impossible'
        options:
          - 'ghcr.io/create-the-roaring-impossible'
      dockerfile:
        description: 'Set the Dockerfile to use'
        type: choice
        required: true
        default: './dockerfiles/tf.dockerfile'
        options:
          - './dockerfiles/tf.dockerfile'
      tag:
        description: 'Set the image to build'
        type: string
        required: true
        default: '1.0.0'
      isRC:
        description: 'Is this a Release Candidate?'
        type: boolean
        required: true
        default: false
jobs:
  docker:
    name: 'Docker - Build And Push'
    runs-on: 'docker'
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.DOCKER_TOKEN}}
######################################################################################################################################################
      - name: 'Build and Push'
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './dockerfiles/tf.dockerfile'
          push: true
          # TODO: to pass second tag as input
          tags: |
            ghcr.io/create-the-roaring-impossible/tf:latest
            ghcr.io/create-the-roaring-impossible/tf:1.0.0
          labels: |
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.created=${{steps.date.outputs.date}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.version=1.0.0
            org.opencontainers.image.licenses=gpl-3.0
            org.opencontainers.image.authors=${{secrets.AUTHOR_EMAIL}}