name: 'SonarQube Scan'
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarQubeScan:
    # TODO: to run on a specific container
    name: SonarQube
    runs-on: 'docker' # TODO: to use the new pool
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}