name: 'Terraform CI\CD'
on:
  workflow_dispatch:
#   push:
#     branches:
#       - master
#   pull_request:
#     types: [opened, synchronize, reopened]
jobs:
  terraform:
    name: Terraform
    runs-on: 'arc-desktop-s8glse7'
    container:
      image: ghcr.io/create-the-roaring-impossible/tf:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
      options: --user 1001
    steps:
      - name: Terraform Init
        run: |
          terraform --version
          ls -larth
      - name: 'Repository Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
        #   clean: false
        #   set-safe-directory: false