name: 'Terraform Docs & Scan'
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TERRAFORM_FOLDER: 'terraform/'
jobs:
  terraformDocsAndScan:
    name: 'Terraform Docs And Scan'
    runs-on: 'arc-desktop-s8glse7'
    container:
      image: ghcr.io/create-the-roaring-impossible/tf:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy some files in all environment folders
        shell: bash
        run: |
          for subdir in $(find ${TERRAFORM_FOLDER} -mindepth 2 -maxdepth 2 -type d); do
            if [[ "$(basename $subdir)" == "docs" ]]; then
              echo "Skipping $subdir folder"
              continue
            fi
            parent_dir=$(dirname $subdir)
            echo "Copying to: $subdir"
            cp $parent_dir/backend.tf $subdir/backend.tf
            cp $parent_dir/variables.tf $subdir/variables.tf
            cp -r $parent_dir/docs/ $subdir/docs/
          done
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          atlantis-file: '${{ env.TERRAFORM_FOLDER }}atlantis.yaml'
          config-file: 'docs/.terraform-docs.yml'
          git-commit-message: 'Update documentation and scan reports - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          git-push: 'true'
          git-push-user-email: 'github@fake-domain.lol'
          git-push-user-name: 'GitHub Bot'
      - name: Delete some files in all environment folders
        shell: bash
        run: |
          for subdir in $(find ${TERRAFORM_FOLDER} -mindepth 2 -maxdepth 2 -type d); do
            if [[ "$(basename $subdir)" == "docs" ]]; then
              echo "Skipping $subdir folder"
              continue
            fi
            echo "Cleaning: $subdir"
            rm -f $subdir/backend.tf $subdir/variables.tf
            rm -rf $subdir/docs/
          done