name: 'Terraform Docs & Scan'
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TERRAFORM_FOLDER: 'terraform/'
  TERRAFORM_DOCS_FOLDER: 'docs'
jobs:
  terraformDocsAndScan:
    name: 'Terraform Docs And Scan'
    runs-on: 'arc-desktop-s8glse7'
    permissions:
      contents: write
      pull-requests: write
    container:
      image: ghcr.io/create-the-roaring-impossible/tf:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Copy some files, formatting and scanning, in all environment folders
        shell: bash
        run: |
          for subdir in $(find ${TERRAFORM_FOLDER} -mindepth 2 -maxdepth 2 -type d); do
            if [[ "$(basename $subdir)" == "${TERRAFORM_DOCS_FOLDER}" ]]; then
              echo "Skipping $subdir folder"
              continue
            fi
            parent_dir=$(dirname $subdir)
            echo "Copying files to: $subdir"
            cp $parent_dir/backend.tf $subdir/backend.tf
            cp $parent_dir/variables.tf $subdir/variables.tf
            cp -r $parent_dir/${TERRAFORM_DOCS_FOLDER}/ $subdir/${TERRAFORM_DOCS_FOLDER}/
            terraform fmt
            tfsec --format markdown --out $subdir/tfsec.report --tfvars-file $subdir/terraform.tfvars . || true
          done
      - name: Generate Terraform documentation
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          atlantis-file: '${{ env.TERRAFORM_FOLDER }}atlantis.yaml'
          config-file: '${{ env.TERRAFORM_DOCS_FOLDER }}/.terraform-docs.yml'
          git-push: 'false'
      - name: Delete some files in all environment folders
        shell: bash
        run: |
          for subdir in $(find ${TERRAFORM_FOLDER} -mindepth 2 -maxdepth 2 -type d); do
            if [[ "$(basename $subdir)" == "${TERRAFORM_DOCS_FOLDER}" ]]; then
              echo "Skipping $subdir folder"
              continue
            fi
            echo "Cleaning files from: $subdir"
            rm -f $subdir/backend.tf $subdir/variables.tf
            rm -rf $subdir/${TERRAFORM_DOCS_FOLDER}/
          done
      - name: Commit and push new documentation and scan reports
        shell: bash
        run: |
          # Configure git
          git config --global --add safe.directory '*'
          git config --global user.email "github@fake-domain.lol"
          git config --global user.name "GitHub Bot"
          # Check the current status
          git status
          # Commit and push
          git add .
          git commit -m "Update documentation and scan reports - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" || true
          git push origin HEAD:refs/heads/${{ github.event.pull_request.head.ref }}