name: 'Terraform CI\CD'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Set the environment'
        type: choice
        required: true
        default: 'dev'
        options:
          - 'dev'
          - 'test'
          - 'prod'
      # tag:
      #   description: 'Set the tag to build'
      #   type: string
      #   required: true
      #   default: '1.0.0'
      # isRC:
      #   description: 'Is this a Release Candidate?'
      #   type: boolean
      #   required: true
      #   default: true
jobs:
  terraform:
    name: Terraform
    runs-on: 'arc-desktop-s8glse7'
    container:
      image: ghcr.io/create-the-roaring-impossible/tf:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: 'Repository Checkout'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Terraform Init
        run: |
          pwsh scripts/pwsh/terraform.ps1